name: Locust Load Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install locust

      - name: Run Locust Load Test
        run: |
          locust -f locust/locustfile.py --headless -u 10 -r 2 --run-time 1m --host http://127.0.0.1:5000
